### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by anseljh** [commonform/commonform-cli#17]
https://libraries.io/github/commonform/commonform-cli shows istanbul and stream-buffers are on old versions.

**Comment by kemitchell** [comment]
Thanks for this.

Feel free to upgrade whatever you want. I typically don't care either way if deps go out of date, so long as they're not shared deps we should be deduplicating for packing in the browser script for commonform.org.

**Comment by kemitchell** [comment]
Closed by 560cfa8bb69ef59355e96cfd3b2a129d4452633f and f064e1c91c8db66021108ef7c1975e3fecad3619

`npm outdated` is no output for now.
