### ISSUE TITLE
Standard Command line Args or Explanation of piping

### ISSUE THREAD

**Issue by tbrooke** [commonform/commonform-cli#21]
It is confusing because in my experience most CLI interfaces use command line arguments rather than linux piping. So maybe some examples under the help flag would help

Or use standard Command line arguments, maybe a library like [Command Line Args](https://github.com/75lb/command-line-args)

Or an explanation of Linux piping in the documentation: [Linux Tutorial](http://ryanstutorials.net/linuxtutorial/piping.php#introduction)

**Comment by kemitchell** [comment]
I wouldn't be against an optional file agument or a `--file` flag.

In terms of immediate need, would it be best just to give usage examples in README?
